# .github/dependabot.yml

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "fix"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "fix"
    open-pull-requests-limit: 5

  # Enable security updates
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2
    insecure-external-code-execution: "deny"
