version: '3'

services:
  nginx-proxy:
    container_name: nginx-proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - green-frontend
      - green-app
    networks:
      - saas-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  green-frontend:
    container_name: green-frontendd
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    networks:
      - saas-network

  green-app:
    container_name: green-app-service
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    networks:
      - saas-network

networks:
  saas-network:
    external: true
