# version: '3'
# services:
#   nginx-proxy:
#     container_name: nginx-proxy
#     build:
#       context: ./nginx
#       dockerfile: Dockerfile
#     ports:
#       - "80:80"
#     depends_on:
#       - green-frontend
#       - green-app-service
#     networks:
#       - default

#   green-frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     ports:
#       - "8083:80" # Change the host port to 8083 to avoid conflict
#     networks:
#       - default

#   green-app-service:
#     container_name: green-app-service
#     build:
#       context: ./server
#       dockerfile: Dockerfile
#     ports:
#       - "3003:3000"
#     networks:
#       - default

# networks:
#   default:
#     external:
#       name: saas-network 
version: '3'

services:
  nginx-proxy:
    container_name: nginx-proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - green-frontend
      - green-app-service
    networks:
      - saas-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # ✅ Ensure you're mounting the correct config file

  green-frontend:
    container_name: green-frontendd
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    networks:
      - saas-network

  green-app-service:
    container_name: green-app-servicee
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    networks:
      - saas-network

networks:
  saas-network:
    external: true
