version: '3'
services:
  nginx-proxy:
    container_name: nginx-proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - green-frontend
      - green-app-service
    networks:
      - default

  green-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8083:80" # Change the host port to 8083 to avoid conflict
    networks:
      - default

  green-app-service:
    container_name: green-app-service
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3000" # Change the host port to 3001 to avoid conflict
    networks:
      - default

networks:
  default:
    driver: bridge
