# docker-compose.yml
version: '3.8' # Specify a supported version

services:
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Jaeger Collector HTTP endpoint

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Prometheus configuration
    ports:
      - '9090:9090' # Prometheus UI

  grafana:
    image: grafana/grafana
    ports:
      - '3001:3000' # Grafana UI
    volumes:
      - grafana-storage:/var/lib/grafana # Persistent storage for Grafana

volumes:
  grafana-storage:
