name: 🔍 SLA Monitor

on:
  schedule:
    - cron: '0 0 * * *' # runs daily at midnight UTC
  workflow_dispatch:     # allows manual run

jobs:
  check-sla:
    runs-on: ubuntu-latest

    steps:
      - name: 🧠 Check SLA Violations
        uses: actions/github-script@v7
        with:
          script: |
            const issues = await github.paginate(
              github.rest.issues.listForRepo,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: "open",
              }
            );

            const today = new Date();
            const violatedLabel = 'sla/violated';

            for (const issue of issues) {
              const labels = issue.labels.map(l => l.name);
              if (labels.includes('sla/48h') || labels.includes('sla/7d') || labels.includes('sla/14d')) {
                const created = new Date(issue.created_at);
                const deadline = new Date(created);

                if (labels.includes('sla/48h')) deadline.setDate(created.getDate() + 2);
                if (labels.includes('sla/7d')) deadline.setDate(created.getDate() + 7);
                if (labels.includes('sla/14d')) deadline.setDate(created.getDate() + 14);

                if (today > deadline && !labels.includes(violatedLabel)) {
                  await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number,
                    body: `⚠️ SLA violated! This issue was expected to be resolved by **${deadline.toDateString()}**. Please take action.`,
                  });

                  await github.rest.issues.addLabels({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number,
                    labels: [violatedLabel],
                  });
                }
              }
            }
