# name: CI Pipeline

# on:
#   push:
#     branches: [main, dev]
#   pull_request:
#     branches: [main, dev]

# jobs:
#   test:
#     name: Matrix Test on Node.js
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [16.x, 18.x, 20.x]

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: 'npm'

#       - name: Install dependencies
#         run: npm ci

#       - name: Run unit tests (if exists)
#         run: |
#           if npm run | grep -q "test:unit"; then
#             npm run test:unit
#           else
#             echo "No unit test script found."
#           fi

#       - name: Run integration tests (if exists)
#         run: |
#           if npm run | grep -q "test:integration"; then
#             npm run test:integration
#           else
#             echo "No integration test script found."
#           fi

#       - name: Run E2E tests (if exists)
#         run: |
#           if npm run | grep -q "test:e2e"; then
#             npm run test:e2e
#           else
#             echo "No E2E test script found."
#           fi

#       - name: Upload test reports (optional)
#         if: always()
#         uses: actions/upload-artifact@v4
#         with:
#           name: test-reports-${{ matrix.node-version }}
#           path: reports/
#         continue-on-error: true

#   audit:
#     name: Security Audit
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18.x

#       - name: Install dependencies
#         run: npm ci

#       - name: Run audit check
#         run: |
#           npm audit --omit=dev --json > audit.json || echo "npm audit failed, continuing..."
name: CI Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  unit-tests:
    name: Unit Tests on Node.js
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests (if exists)
        run: |
          if npm run | grep -q "test:unit"; then
            npm run test:unit
          else
            echo "No unit test script found."
          fi

      - name: Upload unit test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report-${{ matrix.node-version }}
          path: reports/
        continue-on-error: true

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run integration tests (if exists)
        run: |
          if npm run | grep -q "test:integration"; then
            npm run test:integration
          else
            echo "No integration test script found."
          fi

      - name: Upload integration test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-report
          path: reports/
        continue-on-error: true

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run E2E tests (if exists)
        run: |
          if npm run | grep -q "test:e2e"; then
            npm run test:e2e
          else
            echo "No E2E test script found."
          fi

      - name: Upload E2E test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-report
          path: reports/
        continue-on-error: true

  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Run audit check
        run: |
          npm audit --omit=dev --json > audit.json || echo "npm audit failed, continuing..."
