name: CI Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  unit-tests:
    name: Unit Tests (Matrix)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        project-dir: [server, frontend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ${{ matrix.project-dir }}/node_modules
          key: ${{ runner.os }}-${{ matrix.project-dir }}-${{ matrix.node-version }}-${{ hashFiles(format('{0}/package-lock.json', matrix.project-dir)) }}

      - name: Install dependencies
        working-directory: ${{ matrix.project-dir }}
        run: npm ci --legacy-peer-deps

      - name: Run unit tests
        working-directory: ${{ matrix.project-dir }}
        run: |
          if npm run | grep -q "test:unit"; then
            npx jest --passWithNoTests
          else
            echo "No unit test script found."
          fi

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report-${{ matrix.project-dir }}-${{ matrix.node-version }}
          path: ${{ matrix.project-dir }}/reports/
          if-no-files-found: warn

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.project-dir }}-${{ matrix.node-version }}
          path: ${{ matrix.project-dir }}/coverage/
          if-no-files-found: ignore

  integration-tests:
    name: Integration Tests (server only)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: server/node_modules
          key: ${{ runner.os }}-integration-server-${{ hashFiles('server/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run integration tests
        run: |
          if npm run | grep -q "test:integration"; then
            npm run test:integration
          else
            echo "No integration test script found."
          fi

      - name: Upload integration report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-report
          path: server/reports/
          if-no-files-found: warn

  e2e-tests:
    name: E2E Tests (frontend only)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-e2e-frontend-${{ hashFiles('frontend/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run E2E tests
        run: |
          if npm run | grep -q "test:e2e"; then
            npm run test:e2e
          else
            echo "No E2E test script found."
          fi

      - name: Upload E2E report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-report
          path: frontend/reports/
          if-no-files-found: warn

  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Run audit check
        run: |
          npm audit --omit=dev --json > audit.json || echo "Audit failed"

      - name: Upload audit result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: audit-result
          path: server/audit.json
          if-no-files-found: warn
