# name: Automated Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight
  push:
    branches:
      - dev

jobs:
  dependency-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # 👉 Root directory
      - name: Install root dependencies
        run: npm install

      - name: Audit root dependencies
        run: npm audit --omit=dev --json > audit-root.json || true

      - name: Update root dependencies
        run: npm update

      # 👉 Server directory
      - name: Install server dependencies
        working-directory: server
        run: npm install

      - name: Audit server dependencies
        working-directory: server
        run: npm audit --omit=dev --json > audit-server.json || true

      - name: Update server dependencies
        working-directory: server
        run: npm update

      # 👉 Frontend directory
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Audit frontend dependencies
        working-directory: frontend
        run: npm audit --omit=dev --json > audit-frontend.json || true

      - name: Update frontend dependencies
        working-directory: frontend
        run: npm update

      # 👉 Create pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "chore: update dependencies"
          body: |
            This PR updates dependencies and audit reports for:
            - Root
            - Server
            - Frontend
            Auto-generated by GitHub Actions.
          branch: dep-update-${{ github.run_id }}
          base: dev
