name: Automated Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - dev

jobs:
  dependency-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run audit
        run: npm audit --production --json > audit.json

      - name: Update dependencies if necessary
        run: npm update

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "chore: update dependencies" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:dev

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "chore: update dependencies"
          body: |
            This PR updates project dependencies and resolves any audit warnings.
            Auto-generated by GitHub Actions.
          branch: dev
          base: main
